apiVersion: v2
name: seerr
description: Seerr media request portal
type: application
version: 0.1.0
appVersion: "2"
home: https://github.com/seerr-team/seerr
sources:
  - https://github.com/seerr-team/seerr
