apiVersion: v2
name: calibre-web
description: Web interface for your Calibre e-book library
type: application
version: 0.1.0
appVersion: "0.6"
home: https://github.com/janeczku/calibre-web
sources:
  - https://github.com/janeczku/calibre-web
