apiVersion: v2
name: audiobookshelf
description: Self-hosted audiobook and podcast server
type: application
version: 0.1.0
appVersion: "2"
home: https://www.audiobookshelf.org
sources:
  - https://github.com/advplyr/audiobookshelf
